# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Dot Wiki
site_url: https://tylernguyen.wiki
site_author: Tyler Nguyen
site_description: >-
  .wiki/ is Tyler Nguyen's digital garden and blog.

repo_name: tylernguyen/wiki
repo_url: https://github.com/tylernguyen/wiki
edit_uri: "edit/main/docs/"

copyright: >
  Copyright &copy; 2025 Tyler Nguyen | <a href="https://tylernguyen.wiki/license/">LICENSE</a> <br>
  Analytics by
  <span class="twemoji">
    <img src="https://assets.tylernguyen.wiki/logos/PostHog-logomark-light.svg#only-light">
    <img src="https://assets.tylernguyen.wiki/logos/PostHog-logomark-dark.svg#only-dark">
  </span>
  PostHog | <a href="https://tylernguyen.wiki/privacy-policy/">Privacy Policy</a>

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png
  font: false # NOTE Disable Google Fonts
  logo: assets/logo.png
  features:
    - announce.dismiss # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/?h=dismiss#announcement-bar
    - content.action.view # LINK https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=content+action#code-actions
    #- content.action.edit # LINK https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=content+action#code-actions
    - content.code.annotate # LINK https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code#adding-annotations
    - content.code.copy # LINK https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code#code-copy-button
    - content.footnote.tooltips # LINK https://squidfunk.github.io/mkdocs-material/reference/footnotes/?h=footnote+tooltips#footnote-tooltips
    - content.code.select # LINK https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code#code-selection-button
    - content.tooltips # LINK https://squidfunk.github.io/mkdocs-material/reference/tooltips/#improved-tooltips
    - navigation.footer # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=footer#navigation
    - navigation.indexes # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages INCOMPATIBLE with toc.integrate (Attach Top Level Doc to Section )
    #- navigation.instant # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    #- navigation.instant.prefetch # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-prefetching
    #- navigation.instant.progress # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#progress-indicator
    # NOTE navigation.instant bugs Giscus. Comments section will not load until page is refreshed
    - navigation.path # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+path#navigation-path
    #- navigation.prune # NOTE Mobile navigation's top level chevron cannot be selected
    #- navigation.sections # NOTE Collapse section in projects page
    #- navigation.expand # Note Bug: this will also expand collapsed code blocks on page reload
    - navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.top # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation#back-to-top-button
    - navigation.tracking # NOTE Update URL with Active Anchor
    - search.highlight # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+high#search-highlighting
    - search.suggest # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+high#search-suggestions
    - toc.follow # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation#anchor-following
    #- toc.integrate # NOTE Table of Contents as part of Navigation INCOMPATIBLE with navigation.indexes
  icon:
    repo: simple/refinedgithub
    annotation: octicons/comment-24
    search: material/magnify-expand
    top: octicons/move-to-top-24
    view: octicons/markdown-16
    admonition:
      note: octicons/pencil-16
      abstract: octicons/log-16
      info: octicons/report-16
      tip: octicons/hubot-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/package-16
    tag:
      default: octicons/tag-16
      Evergreen: material/leaf
      MTG: material/cards
      MkDocs: simple/materialformkdocs
      Mastodon: simple/mastodon
      Typography: octicons/typography-16
      Design: octicons/paintbrush-16
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/lightbulb-auto-outline
        name: "Automatic Mode Enabled. Click to Toggle Dark Mode."
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-night-outline
        name: "Dark Mode Enabled. Click to Toggle Light Mode."
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: "Light Mode Enabled. Click to Toggle Automatic Mode."

    # - scheme: slate
    #   primary: custom
    #   toggle:
    #     icon: material/lightbulb-night-outline
    #     name: Dark Mode Enabled. Click to Toggle Light Mode.

    # - scheme: default
    #   toggle:
    #     icon: material/lightbulb-outline
    #     name: Light Mode Enabled. Click to Toggle Automatic Mode.

extra:
  analytics:
    provider: posthog
  # consent:
  #   actions:
  #     - accept
  #     - reject
  #     - manage
  #   title: Analytics Cookie
  #   description: >-
  #     PostHog's browser cookie gives me insights into how you interact with .wiki <br>
  #     Rejecting the cookie will not affect your experience with the site. <br> <br>
  #     I do however, ask that you please accept it in order to help me build a more effective website.
  #   cookies:
  #     analytics: PostHog
  generator: false
  social:
    - icon: simple/mastodon
      link: https://tylernguyen.social/@tylernguyen
    - icon: simple/bluesky
      link: https://bsky.app/profile/tylernguyen.social
    - icon: simple/github
      link: https://github.com/tylernguyen
    - icon: simple/forgejo
      link: https://tylernguyen.codes/explore/repos
  tags:
    Evergreen: Evergreen
    MkDocs: MkDocs
    Design: Design

extra_css:
  - stylesheets/solarized.css
  - stylesheets/custom.css
  - stylesheets/typeface.css
  - stylesheets/simpleicons.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

watch:
  - includes

# ANCHOR Plugins
plugins:
  - meta  # NOTE Located at the beginning of the list of `plugins` so that other pluginps (including the [built-in blog plugin]) will pick up the set defaults
  - blog:
      blog_dir: .
      blog_toc: false
      post_readtime: false
      archive_toc: false
      draft_if_future_date: true
      post_excerpt: required
      post_url_format: "{date}/{slug}"
      post_url_max_categories: 1
  - group:
      enabled: !ENV [CI, false]
      plugins:
        - git-revision-date-localized:
            fallback_to_build_date: true
            enable_creation_date: true
            type: timeago
            exclude:
              - archive/*
              - category/*
        - rss:
            match_path: posts/.*
            date_from_meta:
              as_creation: date.created
              as_update: date.updated
            categories:
              - categories
              - tags
            comments_path: "#__comments"
  - privacy:
      assets_exclude:
        - unpkg.com/mathjax@3/*
        - giscus.app/*
  - optimize:
      optimize_png_speed: 1
      optimize_jpg_quality: 30
  - search
  - tags:
      shadow_tags_prefix: _
  - typeset
  - minify:
      minify_js: false
      minify_css: true
      css_files:
        - stylesheets/solarized.css
        - stylesheets/custom.css
        - stylesheets/typeface.css
        - stylesheets/simpleicons.css

# ANCHOR Markdown Extensions
markdown_extensions:
  - abbr
  - attr_list # NOTE Grid, Annotations, Images, Buttons
  - md_in_html # NOTE Grid, Annotations, Images
  - footnotes
  - tables # NOTE Markdown Table
  - toc:
      permalink: true
  - material.extensions.preview # LINK https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=instant+previ#automatic-previews
  - pymdownx.blocks.admonition:
      types:
      - note
      - abstract
      - info
      - question
      - success
      - tip
      - warning
      - bug
      - failure
      - danger
      - example
      - quote
      - announce
      - extension
      - setting
  - pymdownx.blocks.caption
  - pymdownx.blocks.definition
  - pymdownx.blocks.details:
      types:
      - name: details-note
        class: note
      - name: details-abstract
        class: abstract
      - name: details-info
        class: info
      - name: details-question
        class: question
      - name: details-tip
        class: tip
      - name: details-warning
        class: warning
      - name: details-bug
        class: bug
      - name: details-failure
        class: failure
      - name: details-danger
        class: danger
      - name: details-example
        class: example
      - name: details-quote
        class: quote
      - name: details-announce
        class: announce
      - name: details-extension
        class: extension
      - name: details-setting
        class: setting
  - pymdownx.blocks.tab:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.fancylists:
      inject_style: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true # NOTE Syntax highlighting on code blocks and inline code blocks
      line_spans: __span # NOTE Syntax highlighting on code blocks and inline code blocks
      pygments_lang_class: true # NOTE Add a CSS class to identify the language of the code block
  - pymdownx.inlinehilite
  - pymdownx.saneheaders
  - pymdownx.snippets:
      url_download: true
      auto_append:
      - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences: # NOTE Admoniton, Annotations, MermaidJS
      custom_fences:
        - name: md-render
          class: md-render
          format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.tasklist:
      custom_checkbox: true
  - tools.collapse_code:
      expand_text: ''
      collapse_text: ''
  - pymdownx.arithmatex:
      generic: true

# ANCHOR Navigation tree
nav:
    - Blog:
      - index.md
    - Projects:
      - projects/index.md
      - X1C6 Hackintosh:
        - projects/x1c6-hackintosh/README.md
        - projects/x1c6-hackintosh/datasheet.md
        - projects/x1c6-hackintosh/hardware.md
        - projects/x1c6-hackintosh/BIOS.md
        - projects/x1c6-hackintosh/install-macOS.md
        - projects/x1c6-hackintosh/post-install.md
        - projects/x1c6-hackintosh/issues.md
        - projects/x1c6-hackintosh/checklist.md
        - Technical:
          - projects/x1c6-hackintosh/config.plist.md
          - projects/x1c6-hackintosh/ACPI-patches.md
          - projects/x1c6-hackintosh/keyboard-queries.md
          - projects/x1c6-hackintosh/EC-queries.md
          - projects/x1c6-hackintosh/ALC285.md
          - projects/x1c6-hackintosh/external.md
    - Catalog:
      - favorites.md
      - websites.md
    - Uses:
      - dotfiles.md
      - hardware.md
      - fitness.md
      - peripherals.md
      - workshop.md
      - software.md
      - services.md
      - self-hosted.md
    - Contact:
      - contact.md
      - ident.md
    - About:
      - about.md
      - license.md
      - privacy-policy.md
    - Support: https://github.com/sponsors/tylernguyen
    - credits.md
